### ISSUE TITLE
Configuration option to listen on only specific interfaces, rather than all of them

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucetagent#23]
The server agent currently starts the gRPC server listening port on all interfaces:
```
    server.add_secure_port('[::]:%d' % gnmi_port, credentials)
```
It would be nice to make that configurable, for cases where you might want to specify as particular interface to listen on, for example `127.0.0.1`.

**Comment by lantz** [comment]
Feel free to submit a pull request btw
