### ISSUE TITLE
Agent should test via faucetsdn's travis instance

### ISSUE THREAD

**Issue by lantz** [faucetsdn/faucetagent#28]
@gizmoguy  It seems like we should be using `faucetsdn`'s travis - is it possible to activate that integration?

Then we can change the banner in `README.md` as well.

**Comment by gizmoguy** [comment]
Oh yeah, I can activate that. Will assign to myself and get it done before the dev call next week.

**Comment by gizmoguy** [comment]
Hi @lantz, I just checked this and you're already enabled in the faucetsdn travis. I just checked and it seems to be building regularly for you on all your PRs and merged branches.

Here is your badge:

`[![Build Status](https://travis-ci.com/faucetsdn/faucetagent.svg?branch=master)](https://travis-ci.com/faucetsdn/faucetagent)`

**Comment by lantz** [comment]
Oh, I was looking at `travis-ci.org` rather than `travis-ci.com`.
Added #29
